name: huawei_fido_example
description: Demonstrates how to use the huawei_fido plugin.
version: 5.0.5+305

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  huawei_fido: ^5.0.5+305

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true